# SVD

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1], [-2, 2], [-1, -1]])

print("A:")
print(A)

A:
[[ 1  1]
 [-2  2]
 [-1 -1]]


In [3]:
U = np.array([[1/1.414, 0, 1/1.414], [0, 1, 0], [-1/1.414, 0, 1/1.414]])

UU = U[:,:1]

print("U:")
print(U)
print("UU:")
print(UU)

U:
[[ 0.70721358  0.          0.70721358]
 [ 0.          1.          0.        ]
 [-0.70721358  0.          0.70721358]]
UU:
[[ 0.70721358]
 [ 0.        ]
 [-0.70721358]]


In [4]:
D = np.array([[4, 0], [0, 1/1.414], [0, 0]])

DD = D[:1,:1]

print("D")
print(D)

print("DD")
print(DD)

D
[[4.         0.        ]
 [0.         0.70721358]
 [0.         0.        ]]
DD
[[4.]]


In [5]:
Vt = np.array([[1/1.414, 1/1.414], [-1/1.414, 1/1.414]])

VVt = Vt[:1,:]

print("Vt")
print(Vt)

print("VVt")
print(VVt)

Vt
[[ 0.70721358  0.70721358]
 [-0.70721358  0.70721358]]
VVt
[[0.70721358 0.70721358]]


In [6]:
AA = U @ D @ Vt

print("AA")
print(AA)

AA
[[ 2.00060418  2.00060418]
 [-0.50015105  0.50015105]
 [-2.00060418 -2.00060418]]


In [7]:
UU @ DD @ VVt

array([[ 2.00060418,  2.00060418],
       [ 0.        ,  0.        ],
       [-2.00060418, -2.00060418]])

# PCA

In [8]:
import numpy as np
from sklearn.decomposition import PCA

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)


PCA(n_components=2)

In [9]:
print(pca.explained_variance_ratio_)


[0.99244289 0.00755711]


In [10]:
print(pca.singular_values_)

[6.30061232 0.54980396]


In [11]:
print(pca.components_)


[[-0.83849224 -0.54491354]
 [ 0.54491354 -0.83849224]]
